Repository algolia/cli, pull requests merged in 2023-01, with the labels that each got.

#94 [DEX-307] dictionary entries browse
  pkg/cmd/dictionary/entries/browse/browse.go
  pkg/cmd/dictionary/entries/browse/browse_test.go
  pkg/cmd/dictionary/entries/clear/clear.go
  pkg/cmd/dictionary/entries/entries.go
  pkg/cmd/dictionary/shared/constants.go
Labels: enhancement

#92 [DEX-301] feat: algolia objects operations
  pkg/cmd/objects/objects.go
  pkg/cmd/objects/operations/operations.go
  pkg/cmd/objects/operations/operations_test.go
  pkg/cmd/objects/update/update.go
  pkg/cmd/objects/update/update_test.go
Labels: enhancement

#93 [DEX-332] Add events tail command
  api/insights/client.go
  api/insights/responses.go
  api/insights/types.go
  api/insights/utils.go
  pkg/cmd/events/events.go
  pkg/cmd/events/tail/tail.go
  pkg/cmd/root/root.go
Labels: enhancement

#100 [DEX-381] fix: algolia apikeys list json
  pkg/cmd/apikeys/list/list.go
Labels: bug

#101 [DEX-401] fix: algolia search usage
  pkg/cmd/search/search.go
Labels: documentation

#95 [DEX-308] feat: algolia dictionary entries import
  pkg/cmd/dictionary/entries/entries.go
  pkg/cmd/dictionary/entries/import/import.go
  pkg/cmd/dictionary/entries/import/import_test.go
  pkg/cmd/dictionary/shared/constants.go
  pkg/cmd/objects/update/object.go
Labels: enhancement
